apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-dp
  labels:
    app: kuber-dp
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: kuber-app
        image: roflmaoinmysoul/otus:v0.1
        ports:
        - containerPort: 8000
        env:
        - name: DB_USR
          valueFrom:
            secretKeyRef:
              name: kuber-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: kuber-secret
              key: password