apiVersion: v1
kind: Pod
metadata:
  name: app-kuber-label-1
  labels:
    env: prod
spec:
  containers:
  - name: app-kuber-container
    image: roflmaoinmysoul/otus:v0.1
    ports:
    - containerPort: 8000