apiVersion: v1
kind: Service
metadata:
  name: kuber-service
  labels:
    env: prod
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    env: prod
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kuber-ss
spec:
  selector:
    matchLabels:
      env: prod
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: kuber-app2
        image: roflmaoinmysoul/otus:v0.1
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: volume
          mountPath: /cache
  volumeClaimTemplates:
  - metadata:
      name: volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ""
      resources:
        requests:
          storage: 1Gi